---
- name: Prepare servers
  hosts: all
  become: true
  tags: prepare

  pre_tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: true

  roles:
    - geerlingguy.docker

- name: Deploy n8n via Docker Compose
  hosts: n8n
  become: true
  tags: n8n
  tasks:
    - name: Ensure n8n directory exists
      ansible.builtin.file:
        path: /opt/n8n
        state: directory
        owner: root
        group: root
        mode: "755"

    - name: Create .env file
      ansible.builtin.template:
        src: .env.j2
        dest: /opt/n8n/.env
        owner: root
        group: root
        mode: "755"

      become: true

    - name: Run n8n container
      community.docker.docker_container:
        name: n8n
        image: docker.n8n.io/n8nio/n8n:2.9.1
        state: started
        restart_policy: unless-stopped
        env_file: /opt/n8n/.env
        published_ports:
          - "{{ n8n_port }}:5678"
        volumes:
          - "n8n_/home/node/.n8n"
        pull: true
