---
- name: Prepare servers
  hosts: all
  become: true
  tags: prepare

  pre_tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: true

  roles:
    - geerlingguy.docker

- name: Deploy n8n via Docker Compose
  hosts: n8n
  become: true
  tags: n8n
  tasks:
    - name: Ensure n8n directory exists
      ansible.builtin.file:
        path: /opt/n8n
        state: directory
        owner: root
        group: root
        mode: "755"

    - name: Create .env file
      ansible.builtin.template:
        src: .env.j2
        dest: /opt/n8n/.env
        owner: root
        group: root
        mode: "755"

      become: true

    - name: Run n8n container
      community.docker.docker_container:
        name: n8n
        image: docker.n8n.io/n8nio/n8n:2.9.1
        state: started
        restart_policy: unless-stopped
        env_file: /opt/n8n/.env
        published_ports:
          - "{{ vault_n8n_port }}:5678"
        volumes:
          - "n8n_/home/node/.n8n"
        pull: true

- name: Install Datadog agent
  hosts: n8n
  become: true
  tags: monitoring

  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      ansible.builtin.import_role:
        name: datadog.dd.agent

    - name: Configure Datadog HTTP check
      ansible.builtin.template:
        src: templates/http_check.yml.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/n8n.yml
        owner: dd-agent
        group: dd-agent
        mode: "0644"
      notify: restart datadog-agent
      tags: datadog

    - name: Ensure Datadog agent is running
      ansible.builtin.service:
        name: datadog-agent
        state: restarted
        enabled: true
      tags: datadog

- name: Generate Terraform secrets
  hosts: localhost
  tags: terraform

  tasks:
    - name: Generate backend vars
      ansible.builtin.template:
        src: templates/tf_secrets/secret.backend.tfvars.j2
        dest: ../terraform/secret.backend.tfvars
        mode: "0644"

    - name: Generate auto vars
      ansible.builtin.template:
        src: templates/tf_secrets/secret.auto.tfvars.j2
        dest: ../terraform/secret.auto.tfvars
        mode: "0644"
